title: ROMOOOOO
description: Research in offensive security and bug bounties.
baseurl: ""
url: "https://romooooo.github.io/"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
plugins: ['jekyll-feed']
exclude: [README.md, vendor]
